-- CICD-VAR: ADMIN_ROLE_NAME
-- CICD-VAR: IMPLEMENTATION_DB_NAME
-- CICD-VAR: PRESENTATION_DB_NAME
-- CICD-VAR: WAREHOUSE_NAME

BEGIN
    USE ROLE {ADMIN_ROLE_NAME};
    USE WAREHOUSE {WAREHOUSE_NAME};
    USE DATABASE {PRESENTATION_DB_NAME};

    CREATE OR REPLACE VIEW SALESFORCE.SALESFORCE_CONTACT
    AS
    SELECT ID, ACCOUNTID, SALUTATION, FIRSTNAME, LASTNAME
    FROM {IMPLEMENTATION_DB_NAME}.SALESFORCE_LOAD.SALESFORCE_CONTACT;

    GRANT OWNERSHIP ON VIEW SALESFORCE.SALESFORCE_CONTACT TO ROLE {ADMIN_ROLE_NAME};
END;
