-- CICD-SCRIPT-TYPE: CREATE_ROLE
-- CICD-ROLE-NAME: {ADMIN_ROLE_NAME}
-- CICD-VAR: ENV
-- CICD-VAR: SERVICE_USER_NAME
-- CICD-VAR: ADMIN_ROLE_NAME
-- CICD-VAR: EXISTING_ROLE_COUNT
-- CICD-VAR: WAREHOUSE_NAME

DECLARE 
    object_count INT DEFAULT {EXISTING_ROLE_COUNT};
BEGIN
    USE ROLE ACCOUNT_OBJECT_CREATOR;
    USE WAREHOUSE {WAREHOUSE_NAME};

    IF (object_count = 0) THEN
        CREATE ROLE {ADMIN_ROLE_NAME};
        GRANT OWNERSHIP ON ROLE {ADMIN_ROLE_NAME} TO ROLE {ENV}SECURITYADMIN;
    END IF;

    USE ROLE {ENV}ADMIN;
    GRANT ROLE {ADMIN_ROLE_NAME} TO ROLE {ENV}SYSADMIN;
    GRANT ROLE {ADMIN_ROLE_NAME} TO USER {SERVICE_USER_NAME};
END;