-- CICD-VAR: ENV
-- CICD-VAR: ADMIN_ROLE_NAME
-- CICD-VAR: WAREHOUSE_NAME

DECLARE
    env VARCHAR(10) DEFAULT '{ENV}';
BEGIN
    USE ROLE {ENV}ADMIN;
    USE WAREHOUSE {WAREHOUSE_NAME};

    IF (env='PROD') THEN
        GRANT USAGE ON WAREHOUSE PROD_GENERAL TO ROLE {ADMIN_ROLE_NAME};
        GRANT USAGE ON WAREHOUSE PROD_ELT TO ROLE {ADMIN_ROLE_NAME};
    ELSE
        GRANT USAGE ON WAREHOUSE NON_PROD_ALL TO ROLE {ADMIN_ROLE_NAME};
    END IF;
END;