-- CICD-VAR: ADMIN_ROLE_NAME
-- CICD-VAR: READER_ROLE_NAME
-- CICD-VAR: IMPLEMENTATION_DB_NAME
-- CICD-VAR: PRESENTATION_DB_NAME
-- CICD-VAR: WAREHOUSE_NAME

BEGIN
    USE ROLE {ADMIN_ROLE_NAME};
    USE WAREHOUSE {WAREHOUSE_NAME};
    USE DATABASE {IMPLEMENTATION_DB_NAME};

    GRANT ALL ON ALL TABLES IN SCHEMA AG_BEIS_LOAD TO ROLE {ADMIN_ROLE_NAME};

    GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA AG_BEIS_LOAD TO ROLE "BI TEAM MEMBER";

    USE DATABASE {PRESENTATION_DB_NAME};

    GRANT ALL ON ALL VIEWS IN SCHEMA AG_BEIS TO ROLE {ADMIN_ROLE_NAME};

    GRANT SELECT, REFERENCES ON ALL VIEWS IN SCHEMA AG_BEIS TO ROLE {READER_ROLE_NAME};
END;