-- CICD-VAR: ADMIN_ROLE_NAME
-- CICD-VAR: IMPLEMENTATION_DB_NAME
-- CICD-VAR: WAREHOUSE_NAME

BEGIN
    USE ROLE {ADMIN_ROLE_NAME};
    USE WAREHOUSE {WAREHOUSE_NAME};
    USE DATABASE {IMPLEMENTATION_DB_NAME};

    CREATE SCHEMA SALESFORCE_LOAD WITH MANAGED ACCESS;

    GRANT OWNERSHIP ON SCHEMA SALESFORCE_LOAD TO ROLE {ADMIN_ROLE_NAME};

    GRANT ALL ON SCHEMA SALESFORCE_LOAD TO ROLE {ADMIN_ROLE_NAME};
END;