-- CICD-VAR: ADMIN_ROLE_NAME
-- CICD-VAR: IMPLEMENTATION_DB_NAME
-- CICD-VAR: WAREHOUSE_NAME

BEGIN
    USE ROLE {ADMIN_ROLE_NAME};
    USE WAREHOUSE {WAREHOUSE_NAME};
    USE DATABASE {IMPLEMENTATION_DB_NAME};

    CREATE TABLE SALESFORCE_LOAD.ENERGY_USAGE2
    (
        EnergyType          VARCHAR(20),
        YEAR                INT,
        PostCode            VARCHAR(20),
        MeterCount          INT,
        TotalConsumption    NUMBER(24, 12),
        MeanConsumption     NUMBER(24, 12)
    );

    GRANT OWNERSHIP ON TABLE SALESFORCE_LOAD.ENERGY_USAGE2 TO ROLE {ADMIN_ROLE_NAME};
END;
