-- CICD-VAR: ADMIN_ROLE_NAME
-- CICD-VAR: IMPLEMENTATION_DB_NAME
-- CICD-VAR: WAREHOUSE_NAME

BEGIN
    USE ROLE {ADMIN_ROLE_NAME};
    USE WAREHOUSE {WAREHOUSE_NAME};
    USE DATABASE {IMPLEMENTATION_DB_NAME};

    CREATE OR REPLACE TABLE SALESFORCE_LOAD.CONFIG
    (
        ENTITY_NAME            VARCHAR(50),
        PROCESS_FLAG           VARCHAR(1)
    );

    GRANT OWNERSHIP ON TABLE SALESFORCE_LOAD.CONFIG TO ROLE {ADMIN_ROLE_NAME};
END;
