-- CICD-VAR: ADMIN_ROLE_NAME
-- CICD-VAR: IMPLEMENTATION_DB_NAME
-- CICD-VAR: WAREHOUSE_NAME

BEGIN
    USE ROLE {ADMIN_ROLE_NAME};
    USE WAREHOUSE {WAREHOUSE_NAME};
    USE DATABASE {IMPLEMENTATION_DB_NAME};

    CREATE OR REPLACE TABLE SALESFORCE_MODEL.SALESFORCE_CONTACT
    (
        ID                  VARCHAR(20),
        ACCOUNTID           VARCHAR(20),
        SALUTATION          VARCHAR(20),
        FIRSTNAME           VARCHAR(60),
        LASTNAME            VARCHAR(60)
    );

    GRANT OWNERSHIP ON TABLE SALESFORCE_MODEL.SALESFORCE_CONTACT TO ROLE {ADMIN_ROLE_NAME};
END;
