-- CICD-VAR: ADMIN_ROLE_NAME
-- CICD-VAR: IMPLEMENTATION_DB_NAME
-- CICD-VAR: WAREHOUSE_NAME

BEGIN
    USE ROLE {ADMIN_ROLE_NAME};
    USE WAREHOUSE {WAREHOUSE_NAME};
    USE DATABASE {IMPLEMENTATION_DB_NAME};

--    CREATE OR REPLACE FILE FORMAT SALESFORCE_LOAD.BASIC_CSV
--        TYPE = CSV
--        COMPRESSION = GZIP
--        FIELD_DELIMITER = ','
--        SKIP_HEADER = 1
--        BINARY_FORMAT = BASE64;

    CREATE OR REPLACE FILE FORMAT SALESFORCE_LOAD.BASIC_JSON
        TYPE = JSON
        COMPRESSION = GZIP;
-- AWS error: Option FIELD_DELIMITER is not valid for file format type JSON.
-- FIELD_DELIMITER = ','
--        SKIP_HEADER = 1;

    GRANT OWNERSHIP ON FILE FORMAT SALESFORCE_LOAD.BASIC_JSON TO ROLE {ADMIN_ROLE_NAME};

    GRANT USAGE ON FILE FORMAT SALESFORCE_LOAD.BASIC_JSON TO ROLE {ADMIN_ROLE_NAME};
END;
