-- CICD-VAR: ADMIN_ROLE_NAME
-- CICD-VAR: IMPLEMENTATION_DB_NAME
-- CICD-VAR: WAREHOUSE_NAME

BEGIN
    USE ROLE {ADMIN_ROLE_NAME};
    USE WAREHOUSE {WAREHOUSE_NAME};
    USE DATABASE {IMPLEMENTATION_DB_NAME};

    CREATE OR REPLACE TABLE CONFIG.CONFIG_TABLE
    (
        SALESFORCEOBJECTNAME        VARCHAR(50),
        ENABLED                     BOOLEAN,
        SEQUENCENUMBER              INT,
        SELECTCOLUMNS               VARIANT,
        SENSITIVECOLUMNNAMES        VARCHAR,
        PRIMARYKEYCOLUMNNAME        VARCHAR,
        PARTITIONCOLUMNNAME         VARCHAR,
        PARTITIONRANGES             VARCHAR,
        INCREMENTALCOLUMNNAME       VARCHAR,
        INCREMENTALPROCESSTYPE      VARCHAR,
        LASTINCREMENTALVALUEINT     INT,
        LASTINCREMENTALVALUEDT      TIMESTAMP_TZ,
        WIPINCREMENTALVALUEINT      INT,
        WIPINCREMENTALVALUEDT       TIMESTAMP_TZ,
        SNOWFLAKELOADINGTABLENAME   VARCHAR,
        SNOWFLAKETARGETTABLENAME    VARCHAR,
        SALESFORCEAPI               VARCHAR,
        IGNOREMISSINGSOURCECOLUMNS  BOOLEAN,
        EXTRACTTIMEOUTSECONDS       INT,
        LOADTIMEOUTSECONDS          INT,
        MERGETIMEOUTSECONDS         INT
    );

    GRANT OWNERSHIP ON TABLE CONFIG.CONFIG_TABLE TO ROLE {ADMIN_ROLE_NAME};
END;
